### ISSUE TITLE
Not an Issue, Just a thumps up

### ISSUE THREAD

**Issue by Frido-Cpp** [mainSpi/java-trojan#1]
Cool project Here. Maybe you might want to make it more that this https://github.com/thisisnzed/Pandora

**Comment by mainSpi** [comment]
> Cool project Here. Maybe you might want to make it more that this https://github.com/thisisnzed/Pandora

Certainly going to look at it. Still planning on features, and this will help a lot.

**Comment by Frido-Cpp** [comment]
Yeah, I'm not a java developer If i was I could contribute

**Comment by mainSpi** [comment]
> Yeah, I'm not a java developer If i was I could contribute

ideas are also contribution. Thanks!

**Comment by Frido-Cpp** [comment]
wlcm bro :)

**Comment by Frido-Cpp** [comment]
Yoo bro, Please Is there anyway I can contact you? Discord,Telegram?

**Comment by mainSpi** [comment]
> Yoo bro, Please Is there anyway I can contact you? Discord,Telegram?
> 

hehehe#3017 on discord

**Comment by Frido-Cpp** [comment]
okay
