### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Leg2t** [mainSpi/java-trojan#2]
I installed Java and jdk, added jdk to Path and server Opened. However when opening the build thing on other device (same Java setup) it did not work. Any solution?

**Comment by mainSpi** [comment]
Try running # _java --version_ on both machines and let me see the return. Also let me know what are you putting on the Host field on the server side. Are both computers in the same network? if not, you need to properly forward those ports on your router.

**Comment by Leg2t** [comment]
I ran 2 different vps, i dont have them anymore but the installed Java was the newest version. It was on different network i guess. I tried the default options which are localhost and port 1234

**Comment by mainSpi** [comment]
> I ran 2 different vps, i dont have them anymore but the installed Java was the newest version. It was on different network i guess. I tried the default options which are localhost and port 1234

If it was on different networks, then it doesn't make any sense to use "localhost". See, localhost is a intranet thing. You must use your IP, or setup a DDNS. Also don't forget to open that port on your router.

The default options are for testing on a local network, but this app was built and tested to work with other networks, as a trojan should. Closing this as it's not an issue.

**Comment by Leg2t** [comment]
How can i see my port?

**Comment by mainSpi** [comment]
> How can i see my port?

There is a field, right next to the Host one. You can choose whatever you prefer. "1234" is just the default one.
